### ISSUE TITLE
手机兼容问题！！！！！！！！！

### ISSUE THREAD

**Issue by hui928636443** [dfqin/PermissionGrantor#11]
在坚果手机没给权限 hasPermission还是返回true  蛋疼！！！！！！！！

**Comment by dfqin** [comment]
详情见https://www.jianshu.com/p/cdcbd3038902 的4.1
这种跟oppo类似，厂商修改了api，判断权限时直接返回了true，然后使用权限时再弹出厂商的权限对话框。
为了解决这种情况，只能在真正访问敏感权限时，再次判断。
