### ISSUE TITLE
多个权限申请的时候有问题

### ISSUE THREAD

**Issue by jiayuliang1314** [dfqin/PermissionGrantor#12]
多个权限申请的时候有问题，点击拒绝的话，提示就一个

**Comment by jiayuliang1314** [comment]
多个权限申请的时候有问题，弹出tip窗，点击给权限，然后再返回，这个时候，权限窗口会重新弹出

**Comment by dfqin** [comment]
1. 你拒绝的是系统的权限弹窗还是自定义的提示？
2. 点击给权限再返回？是跳转的系统设置给的权限么？如果你跳转的系统设置，没有全部给权限的话，返回肯定还是要弹窗提示的。
