### ISSUE TITLE
红米手机问题

### ISSUE THREAD

**Issue by mengyaCS** [dfqin/PermissionGrantor#2]
红米手机在检测权限后，跳转到设置权限页面，开启权限返回应用后，应用崩溃。

**Comment by dfqin** [comment]
请问能不能提供一下Log，我这里找不到红米手机:( 
另外方便的话可以debug一下，看是授权相关代码崩溃，还是授权结束后，业务代码崩溃？

**Comment by mengyaCS** [comment]
Eclipse咋样引入jar包？

**Comment by dfqin** [comment]
这个里面有资源文件，只引入jar包不行的
