### ISSUE TITLE
定位权限判断错误

### ISSUE THREAD

**Issue by 54binge** [dfqin/PermissionGrantor#3]
专门测试了下，在小米手机上，权限管理显示询问，但是PermissionsUtil.hasPermission判断的是有权限，还有就是国产的手机默认有个倒计时在紧张的按钮上，这个判断就会有问题，试试PermissionChecker

**Comment by dfqin** [comment]
嗯，我已经使用PermissionChecker替代原来的ContextCompat.checkSelfPermission，小米已经测试过没有问题，非常感谢。
