### ISSUE TITLE
请问在某些机型上申请权限提示有“不再询问”按钮，如果用户点击了拒绝并不再询问，那不就不会调用 ActivityCompat.requestPermissions这个方法

### ISSUE THREAD

**Issue by coolBreezes** [dfqin/PermissionGrantor#5]
// 请求权限兼容低版本
    private void requestPermissions(String[] permission) {
        ActivityCompat.requestPermissions(this, permission, PERMISSION_REQUEST_CODE);
    }
您好，请问在某些机型上申请权限提示有“不再询问”按钮，如果用户点击了拒绝并不再询问，那不就不会调用 ActivityCompat.requestPermissions这个方法了，是不是应该用ActivityCompat.shouldShowRequestPermissionRationale(thisActivity,
            Manifest.permission.READ_CONTACTS)
这个方法先进行下判断呢

**Comment by dfqin** [comment]
这种情况下系统不弹窗授权对话框直接返回失败，我的实现里返回失败后可以弹出自己的提示框，我并没有区分是第一次用户拒绝还是“不再询问”的拒绝，所以没必要调用shouldShowRequestPermissionRationale
