### ISSUE TITLE
代码优化问题，

### ISSUE THREAD

**Issue by coolBreezes** [dfqin/PermissionGrantor#6]
private void requestCemera() {
        if (PermissionsUtil.hasPermission(this, Manifest.permission.CAMERA)) {
            Toast.makeText(MainActivity.this, "可以访问摄像头", Toast.LENGTH_LONG).show();
        } else {
            PermissionsUtil.requestPermission(this, new PermissionListener() {
                @Override
                public void permissionGranted(@NonNull String[] permissions) {
                    Toast.makeText(MainActivity.this, "用户授权了访问摄像头", Toast.LENGTH_LONG).show();
                }

                @Override
                public void permissionDenied(@NonNull String[] permissions) {
                    Toast.makeText(MainActivity.this, "用户拒绝了访问摄像头", Toast.LENGTH_LONG).show();
                }
            }, Manifest.permission.CAMERA);
        }
    }

请问第一个if判断为什么不合入到requestPermission中，不然访问摄像头的操作不是会造成代码冗余么

**Comment by dfqin** [comment]
可以合并进来，requestPermission函数在跳转前没有检查权限，分开写在用户已经有权限的情况下减少一次activity跳转
