### ISSUE TITLE
请问PermissionActivity中的isRequireCheck 变量的作用到底是什么呢

### ISSUE THREAD

**Issue by coolBreezes** [dfqin/PermissionGrantor#7]
请问PermissionActivity中的isRequireCheck 变量的作用到底是什么呢
不是太理解哈

 @Override
    protected void onResume() {
        super.onResume();
        if (isRequireCheck) {
            if (PermissionsUtil.hasPermission(this, permission)) {
                permissionsGranted();
            } else {
                requestPermissions(permission); // 请求权限,回调时会触发onResume
                isRequireCheck = false;
            }
        } else {
            isRequireCheck = true;
        }
    }

**Comment by dfqin** [comment]
只是为了区分是否需要判断授权结果。因为当用户拒绝权限时，这个页面我会弹一个对话框，用户可以点击这个对话框跳转到应用设置页面去打开权限，这个时候再返回过来时已经有权限了，在onResume函数可以捕获到这个变化，返回结果给listener
