### ISSUE TITLE
请问这里的PERMISSION_DENIED_APP_OP指的是什么呢

### ISSUE THREAD

**Issue by coolBreezes** [dfqin/PermissionGrantor#8]
public final class PermissionChecker {
    /** Permission result: The permission is granted. */
    public static final int PERMISSION_GRANTED =  PackageManager.PERMISSION_GRANTED;

    /** Permission result: The permission is denied. */
    public static final int PERMISSION_DENIED =  PackageManager.PERMISSION_DENIED;

    /** Permission result: The permission is denied because the app op is not allowed. */
    public static final int PERMISSION_DENIED_APP_OP =  PackageManager.PERMISSION_DENIED  - 1;

请问这里的PERMISSION_DENIED_APP_OP指的是什么呢

**Comment by dfqin** [comment]
没有权限，跟PERMISSION_DENIED含义差不多，为了兼容targetSDKVersion<23使用的
